project_id = "jfpzbsfywfcuylqgafpp"

[functions.create-user-invite]
verify_jwt = true

[functions.check-missed-interviews]
verify_jwt = false

[functions.update-student-statuses]
verify_jwt = false

[functions.email-automation]
verify_jwt = false