// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vibbpmjjfgzfievvserr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpYmJwbWpqZmd6ZmlldnZzZXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0NTQxNTgsImV4cCI6MjA5OTAzMDE1OH0.CasdVPdzJ8FSyggu09OkLPEnhdXVvloAy3YuyQ-ytXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);